const app=document.getElementById('app');
const state={time:'7:00 AM',xp:370,coins:1250,activeBell:null,meds:{}};
const residents=[
{name:'Mrs Thompson',room:1,condition:'Dementia',note:'Increased confusion overnight',meds:['Donepezil','Paracetamol'],skin:'#e7c4ad',hair:'#d8d3cc',top:'#8a5f9d',style:'short'},
{name:'Mr Harris',room:4,condition:'Parkinson’s',note:'Settled well overnight',meds:['Co-careldopa','Ramipril'],skin:'#d7a982',hair:'#b9b5ad',top:'#55758c',style:'side'},
{name:'Mrs Patel',room:6,condition:'Type 2 diabetes',note:'Blood glucose slightly raised',meds:['Metformin','Amlodipine'],skin:'#b97850',hair:'#43342d',top:'#a75f7c',style:'bun'},
{name:'Mr Wilson',room:8,condition:'Post-stroke',note:'Good night',meds:['Aspirin','Atorvastatin'],skin:'#e0b694',hair:'#c9c4bb',top:'#68825c',style:'short'},
{name:'Mrs Carter',room:10,condition:'Mobility support',note:'1:1 for transfers',meds:['Paracetamol'],skin:'#edc9b3',hair:'#eee5dd',top:'#5f789f',style:'wave'},
{name:'Mr Lewis',room:12,condition:'Dementia · high falls risk',note:'Unsettled between 1–3am',meds:['Memantine','Ramipril'],skin:'#d9aa86',hair:'#aaa49d',top:'#7b654f',style:'side'},
{name:'Mrs Green',room:14,condition:'Pain / comfort',note:'Increased pain overnight',meds:['Paracetamol','Omeprazole'],skin:'#efc7a7',hair:'#c8bfb3',top:'#8c6d96',style:'wave'},
{name:'Mr Baker',room:16,condition:'High falls risk',note:'Near fall overnight',meds:['Bisoprolol','Atorvastatin'],skin:'#bd845f',hair:'#8d8881',top:'#526f86',style:'short'}
];
function portrait(r,large=false){
 const hair=r.style==='bun'?`<circle cx="50" cy="19" r="13" fill="${r.hair}"/><path d="M24 42c2-21 14-30 26-30s24 9 26 30l-7-2c-2-14-9-21-19-21s-17 7-19 21z" fill="${r.hair}"/>`:r.style==='wave'?`<path d="M23 44c0-24 12-34 27-34 17 0 28 12 27 35-6-6-11-8-15-11-7 6-20 7-32 2-2 3-4 6-7 8z" fill="${r.hair}"/>`:`<path d="M25 39c2-19 13-28 25-28 14 0 24 8 26 26-8-4-15-6-23-7-9 1-17 4-28 9z" fill="${r.hair}"/>`;
 return `<span class="portrait ${large?'large':''}"><svg viewBox="0 0 100 100" aria-label="Portrait of ${r.name}" role="img"><rect width="100" height="100" rx="18" fill="#ece5df"/><path d="M15 100c3-27 17-40 35-40s32 13 35 40" fill="${r.top}"/>${hair}<ellipse cx="50" cy="43" rx="23" ry="27" fill="${r.skin}"/><ellipse cx="42" cy="43" rx="2.2" ry="2" fill="#3b302b"/><ellipse cx="58" cy="43" rx="2.2" ry="2" fill="#3b302b"/><path d="M46 55c3 2 5 2 8 0" fill="none" stroke="#9d5e59" stroke-width="1.8" stroke-linecap="round"/><path d="M50 45v6" stroke="#b98574" stroke-width="1.3" stroke-linecap="round"/></svg></span>`;
}
function carerFigure(){return `<svg class="carer-svg" viewBox="0 0 80 140" role="img" aria-label="Amy, senior carer"><circle cx="40" cy="25" r="17" fill="#e8b997"/><path d="M23 23c2-15 11-22 19-22 11 0 18 7 18 21-7-5-12-7-18-8-7 1-13 4-19 9z" fill="#5a3c31"/><path d="M20 55c8-8 32-8 40 0v45H20z" fill="#6e3c91"/><rect x="29" y="64" width="22" height="10" rx="3" fill="#fff"/><path d="M26 100l-7 35M54 100l7 35M20 65L8 98M60 65l12 33" stroke="#23366f" stroke-width="9" stroke-linecap="round"/></svg>`}
function header(){return `<header class="game-head"><div><h1>Amy</h1><div>Senior Carer · Level 5</div><div class="xpbar"><i style="width:${Math.min(100,state.xp/5)}%"></i></div><small>${state.xp}/500 XP</small></div><div class="brandmark"><span class="house-mark">⌂</span><b>AMY'S HAVEN</b><small>CARE HOME</small></div><div class="head-right"><div class="coins">★ ${state.coins}　♥ 5</div><div class="clock"><b>${state.time}</b><small>Day Shift · 7:00 AM–7:00 PM</small></div></div></header>`}
function nav(active='Home'){return `<nav class="bottom-nav">${['Home','Residents','Tasks','Medication','Care Plans','Progress','Shop'].map(x=>`<button class="${x===active?'active':''}" onclick="go('${x}')">${x}</button>`).join('')}</nav>`}
function shell(body,active='Home'){app.innerHTML=`<div class="app-shell">${header()}<main>${body}</main>${nav(active)}</div>`;window.scrollTo(0,0)}
function residentCards(){return residents.map(r=>`<button class="resident-row" onclick="resident('${r.name.replace(/'/g,"\\'")}')">${portrait(r)}<span><b>${r.name} · Room ${r.room}</b><small>${r.condition}<br>${r.note}</small></span><strong>›</strong></button>`).join('')}
function dashboard(){shell(`<div class="tabs"><button class="on">Dashboard</button><button onclick="go('Residents')">Residents</button><button onclick="go('Tasks')">Tasks</button><button onclick="go('Medication')">Medication</button><button onclick="go('Care Plans')">Care Plans</button></div><section class="dash-grid"><div class="card"><h2>Today's Priorities</h2><p>☐ Morning medication round<br>☐ Personal care (AM)<br>☐ Breakfast service<br>☐ Pain assessment – Mrs Green<br>☐ Blood glucose – Mrs Patel</p></div><div class="card"><h2>Live Notifications</h2><button class="bell-card" onclick="respondBell('Mr Lewis')"><b>7:00 AM</b><span>Call bell – Room 12</span></button><button class="bell-card" onclick="respondBell('Mrs Patel')"><b>6:58 AM</b><span>Call bell – Room 6</span></button></div></section><section class="card"><div class="split"><h2>Shift Time</h2><b>12:00:00 remaining</b></div><div class="progress"><i></i></div></section><section class="card"><div class="split"><h2>Your Residents Today</h2><span class="pill">8 Residents</span></div>${residentCards()}</section>`) }
function doorFor(room,target=false){const r=residents.find(x=>x.room===room);return `<div class="door ${target?'target':''}"><span class="room-number">${room}</span><span class="door-name">${r?r.name:'Bedroom'}</span></div>`}
function respondBell(name){const r=residents.find(x=>x.name===name);state.activeBell=name;const left=Math.max(1,r.room-2),right=r.room+2;shell(`<section class="card resident-brief">${portrait(r)}<div><h2>Responding to ${r.name}</h2><p>Room ${r.room} · ${r.condition}</p></div></section><section class="corridor"><div class="hall-sign">Bedroom corridor</div><div class="doors">${doorFor(left)}${doorFor(r.room,true)}${doorFor(right)}</div><div class="walker" id="walker">${carerFigure()}</div><div class="floor"></div></section><p class="game-note" id="walkText">Amy is walking to ${r.name}'s room…</p>`,`Home`);setTimeout(()=>{const w=document.getElementById('walker');if(w)w.classList.add('arrived');const t=document.getElementById('walkText');if(t)t.innerHTML=`You have reached <b>${r.name}</b>, Room ${r.room}. <button class="primary" onclick="knockDoor()">Knock on door</button>`},1400)}
function knockDoor(){const r=residents.find(x=>x.name===state.activeBell);const door=document.querySelector('.door.target');if(door){door.classList.add('knock');setTimeout(()=>door.classList.remove('knock'),700)}setTimeout(()=>{shell(`<section class="room-scene"><div class="speech">“Hello, can you help me please?”</div><div class="resident-sprite">${portrait(r,true)}</div></section><section class="card"><div class="resident-detail-head">${portrait(r)}<div><h2>${r.name}</h2><p>Room ${r.room} · ${r.condition}</p></div></div><p>${r.note}</p><div class="choice-grid"><button onclick="finishBell('reassure')">Reassure and ask what they need</button><button onclick="finishBell('assist')">Offer practical assistance</button><button onclick="finishBell('delegate')">Call another carer for support</button></div></section>`,`Residents`)},650)}
function finishBell(type){state.xp+=20;state.time='7:08 AM';shell(`<section class="card success"><h2>Call bell completed</h2><p>You responded to ${state.activeBell}, checked what they needed and recorded the interaction.</p><button class="primary" onclick="dashboard()">Return to dashboard</button></section>`,`Home`)}
function residentsPage(){shell(`<section class="card"><h2>Residents</h2>${residentCards()}</section>`,'Residents')}
function resident(name){const r=residents.find(x=>x.name===name);shell(`<section class="card resident-profile">${portrait(r,true)}<h2>${r.name}</h2><p>Room ${r.room}<br>${r.condition}<br>${r.note}</p><button class="primary" onclick="respondBell('${r.name.replace(/'/g,"\\'")}')">Walk to resident's room</button></section>`,'Residents')}
function medication(){const rows=residents.map((r,ri)=>`<section class="med-card"><div class="med-person">${portrait(r)}<div><h3>${r.name}</h3><small>Room ${r.room}</small></div><span class="pill">MAR</span></div>${r.meds.map((m,mi)=>medRow(r,m,ri,mi)).join('')}</section>`).join('');shell(`<div class="tabs"><button class="on">Medication Round</button><button>PRN</button><button>Refusals</button></div><section class="card info"><b>Simulation:</b> choose what happened for each medicine. This does not provide real prescribing advice.</section>${rows}`,'Medication')}
function medRow(r,m,ri,mi){const key=`${ri}-${mi}`,v=state.meds[key]||'pending';return `<div class="med-line"><div><b>${m}</b><small>Status: ${v}</small></div><div class="med-actions"><button class="${v==='taken'?'taken':''}" onclick="setMed('${key}','taken')">Taken</button><button class="${v==='refused'?'refused':''}" onclick="setMed('${key}','refused')">Refused</button><button class="${v==='withheld'?'withheld':''}" onclick="setMed('${key}','withheld')">Not given</button></div></div>`}
function setMed(key,status){state.meds[key]=status;medication()}
function tasks(){shell(`<section class="card"><h2>Tasks</h2><p>☐ Morning personal care<br>☐ Breakfast and fluids<br>☐ Medication round<br>☐ Care notes<br>☐ Activities<br>☐ Handover</p></section>`,'Tasks')}
function carePlans(){shell(`<section class="card"><h2>Care Plans</h2><p>Select a resident from the Residents page to review their care needs, mobility, communication and preferences.</p></section>`,'Care Plans')}
function go(x){if(x==='Home')dashboard();else if(x==='Residents')residentsPage();else if(x==='Medication')medication();else if(x==='Tasks')tasks();else if(x==='Care Plans')carePlans();else shell(`<section class="card"><h2>${x}</h2><p>This section is ready for the next expansion.</p></section>`,x)}
dashboard();