const app=document.getElementById('app');
const state={time:'7:00 AM',xp:370,coins:1250,activeBell:null,meds:{}};
const residents=[
{name:'Mrs Thompson',age:84,nationality:'British',ethnicity:'White British',from:'Grimsby, Lincolnshire',room:1,condition:'Dementia',note:'Increased confusion overnight',meds:['Donepezil','Paracetamol'],photo:'https://images.pexels.com/photos/5473061/pexels-photo-5473061.jpeg?auto=compress&cs=tinysrgb&w=900'},
{name:'Mr Harris',age:81,nationality:'British',ethnicity:'White British',from:'Hull, East Yorkshire',room:4,condition:'Parkinson’s',note:'Settled well overnight',meds:['Co-careldopa','Ramipril'],photo:'https://images.pexels.com/photos/5710521/pexels-photo-5710521.jpeg?auto=compress&cs=tinysrgb&w=900'},
{name:'Mrs Parker',age:79,nationality:'British',ethnicity:'White British',from:'Leicester, Leicestershire',room:6,condition:'Type 2 diabetes',note:'Blood glucose slightly raised',meds:['Metformin','Amlodipine'],photo:'https://images.pexels.com/photos/8865426/pexels-photo-8865426.jpeg?auto=compress&cs=tinysrgb&w=900'},
{name:'Mr Wilson',age:86,nationality:'British',ethnicity:'White British',from:'Newcastle upon Tyne',room:8,condition:'Post-stroke',note:'Good night',meds:['Aspirin','Atorvastatin'],photo:'https://images.pexels.com/photos/3868618/pexels-photo-3868618.jpeg?auto=compress&cs=tinysrgb&w=900'},
{name:'Mrs Carter',age:88,nationality:'British',ethnicity:'White British',from:'Lincoln, Lincolnshire',room:10,condition:'Mobility support',note:'1:1 for transfers',meds:['Paracetamol'],photo:'https://images.pexels.com/photos/5473083/pexels-photo-5473083.jpeg?auto=compress&cs=tinysrgb&w=900'},
{name:'Mr Lewis',age:83,nationality:'British',ethnicity:'White British',from:'Sheffield, South Yorkshire',room:12,condition:'Dementia · high falls risk',note:'Unsettled between 1–3am',meds:['Memantine','Ramipril'],photo:'https://images.pexels.com/photos/6830381/pexels-photo-6830381.jpeg?auto=compress&cs=tinysrgb&w=900'},
{name:'Mrs Green',age:90,nationality:'British',ethnicity:'White British',from:'Cleethorpes, Lincolnshire',room:14,condition:'Pain / comfort',note:'Increased pain overnight',meds:['Paracetamol','Omeprazole'],photo:'https://images.pexels.com/photos/8560479/pexels-photo-8560479.jpeg?auto=compress&cs=tinysrgb&w=900'},
{name:'Mr Baker',age:78,nationality:'British',ethnicity:'White British',from:'York, North Yorkshire',room:16,condition:'High falls risk',note:'Near fall overnight',meds:['Bisoprolol','Atorvastatin'],photo:'https://images.pexels.com/photos/3868419/pexels-photo-3868419.jpeg?auto=compress&cs=tinysrgb&w=900'}
];
const amyPhoto='https://randomuser.me/api/portraits/women/32.jpg';
function portrait(r,large=false){return `<span class="portrait ${large?'large':''}"><img src="${r.photo}" alt="Care plan photo of ${r.name}" loading="lazy"></span>`}
function carerFigure(){return `<div class="carer-person"><img class="carer-face" src="${amyPhoto}" alt="Amy, senior carer"><div class="carer-neck"></div><div class="carer-uniform"><span class="name-badge">AMY</span></div><div class="carer-leg left"></div><div class="carer-leg right"></div></div>`}
function header(){return `<header class="game-head"><div><h1>Amy</h1><div>Senior Carer · Level 5</div><div class="xpbar"><i style="width:${Math.min(100,state.xp/5)}%"></i></div><small>${state.xp}/500 XP</small></div><div class="brandmark"><span class="house-mark">⌂</span><b>AMY'S HAVEN</b><small>CARE HOME</small></div><div class="head-right"><div class="coins">★ ${state.coins}　♥ 5</div><div class="clock"><b>${state.time}</b><small>Day Shift · 7:00 AM–7:00 PM</small></div></div></header>`}
function nav(active='Home'){return `<nav class="bottom-nav">${['Home','Residents','Tasks','Medication','Care Plans','Progress','Shop'].map(x=>`<button class="${x===active?'active':''}" onclick="go('${x}')">${x}</button>`).join('')}</nav>`}
function shell(body,active='Home'){app.innerHTML=`<div class="app-shell">${header()}<main>${body}</main>${nav(active)}</div>`;window.scrollTo(0,0)}
function residentCards(){return residents.map(r=>`<button class="resident-row" onclick="resident('${r.name.replace(/'/g,"\\'")}')">${portrait(r)}<span><b>${r.name} · Room ${r.room}</b><small>Age ${r.age} · ${r.ethnicity}<br>${r.condition} · ${r.note}</small></span><strong>›</strong></button>`).join('')}
function dashboard(){shell(`<div class="tabs"><button class="on">Dashboard</button><button onclick="go('Residents')">Residents</button><button onclick="go('Tasks')">Tasks</button><button onclick="go('Medication')">Medication</button><button onclick="go('Care Plans')">Care Plans</button></div><section class="dash-grid"><div class="card"><h2>Today's Priorities</h2><p>☐ Morning medication round<br>☐ Personal care (AM)<br>☐ Breakfast service<br>☐ Pain assessment – Mrs Green<br>☐ Blood glucose – Mrs Parker</p></div><div class="card"><h2>Live Notifications</h2><button class="bell-card" onclick="respondBell('Mr Lewis')"><b>7:00 AM</b><span>Call bell – Room 12</span></button><button class="bell-card" onclick="respondBell('Mrs Parker')"><b>6:58 AM</b><span>Call bell – Room 6</span></button></div></section><section class="card"><div class="split"><h2>Shift Time</h2><b>12:00:00 remaining</b></div><div class="progress"><i></i></div></section><section class="card"><div class="split"><h2>Your Residents Today</h2><span class="pill">8 Residents</span></div>${residentCards()}</section>`) }
function doorFor(room,target=false){const r=residents.find(x=>x.room===room);return `<div class="door ${target?'target':''}"><span class="room-number">${room}</span><span class="door-name">${r?r.name:'Bedroom'}</span></div>`}
function respondBell(name){const r=residents.find(x=>x.name===name);state.activeBell=name;const left=r.room===1?2:r.room-1,right=r.room===1?3:r.room+1;shell(`<section class="card resident-brief">${portrait(r)}<div><h2>Responding to ${r.name}</h2><p>Age ${r.age} · ${r.ethnicity} · Room ${r.room} · ${r.condition}</p></div></section><section class="corridor"><div class="hall-sign">Bedroom corridor</div><div class="doors">${doorFor(left)}${doorFor(r.room,true)}${doorFor(right)}</div><div class="walker" id="walker">${carerFigure()}</div><div class="floor"></div></section><p class="game-note" id="walkText">Amy is walking to ${r.name}'s room…</p>`,`Home`);setTimeout(()=>{const w=document.getElementById('walker');if(w)w.classList.add('arrived');const t=document.getElementById('walkText');if(t)t.innerHTML=`You have reached <b>${r.name}</b>, Room ${r.room}. <button class="primary" onclick="knockDoor()">Knock on door</button>`},1400)}
function knockDoor(){const r=residents.find(x=>x.name===state.activeBell);const door=document.querySelector('.door.target');if(door){door.classList.add('knock');setTimeout(()=>door.classList.remove('knock'),700)}setTimeout(()=>{shell(`<section class="room-scene lifelike-room"><img class="room-resident-photo" src="${r.photo}" alt="${r.name} in their room"><div class="room-shade"></div><div class="room-label">Room ${r.room} · ${r.name}</div><div class="speech">“Hello, can you help me please?”</div></section><section class="card"><div class="resident-detail-head">${portrait(r)}<div><h2>${r.name}</h2><p>Age ${r.age} · ${r.ethnicity} · Room ${r.room}</p></div></div><p>${r.condition}<br>${r.note}</p><div class="choice-grid"><button onclick="finishBell('reassure')">Enter and assist</button><button onclick="finishBell('assist')">Ask what they need</button><button onclick="finishBell('delegate')">Call another carer for support</button></div></section>`,`Residents`)},650)}
function finishBell(type){state.xp+=20;state.time='7:08 AM';shell(`<section class="card success"><h2>Call bell completed</h2><p>You responded to ${state.activeBell}, checked what they needed and recorded the interaction.</p><button class="primary" onclick="dashboard()">Return to dashboard</button></section>`,`Home`)}
function residentsPage(){shell(`<section class="card"><h2>Residents</h2>${residentCards()}</section>`,'Residents')}
function resident(name){const r=residents.find(x=>x.name===name);shell(`<section class="card resident-profile"><div class="pill" style="display:inline-block;margin-bottom:10px">Care plan photograph</div>${portrait(r,true)}<h2>${r.name}</h2><p>Age ${r.age}<br>Nationality: ${r.nationality}<br>Ethnicity: ${r.ethnicity}<br>From: ${r.from}<br>Room ${r.room}<br>${r.condition}<br>${r.note}</p><button class="primary" onclick="respondBell('${r.name.replace(/'/g,"\\'")}')">Walk to resident's room</button></section>`,'Residents')}
function medication(){const rows=residents.map((r,ri)=>`<section class="med-card"><div class="med-person">${portrait(r)}<div><h3>${r.name}</h3><small>Age ${r.age} · ${r.ethnicity} · Room ${r.room}</small></div><span class="pill">MAR</span></div>${r.meds.map((m,mi)=>medRow(r,m,ri,mi)).join('')}</section>`).join('');shell(`<div class="tabs"><button class="on">Medication Round</button><button>PRN</button><button>Refusals</button></div><section class="card info"><b>Simulation:</b> choose what happened for each medicine. This does not provide real prescribing advice.</section>${rows}`,'Medication')}
function medRow(r,m,ri,mi){const key=`${ri}-${mi}`,v=state.meds[key]||'pending';return `<div class="med-line"><div><b>${m}</b><small>Status: ${v}</small></div><div class="med-actions"><button class="${v==='taken'?'taken':''}" onclick="setMed('${key}','taken')">Taken</button><button class="${v==='refused'?'refused':''}" onclick="setMed('${key}','refused')">Refused</button><button class="${v==='withheld'?'withheld':''}" onclick="setMed('${key}','withheld')">Not given</button></div></div>`}
function setMed(key,status){state.meds[key]=status;medication()}
function tasks(){shell(`<section class="card"><h2>Tasks</h2><p>☐ Morning personal care<br>☐ Breakfast and fluids<br>☐ Medication round<br>☐ Care notes<br>☐ Activities<br>☐ Handover</p></section>`,'Tasks')}
function carePlans(){shell(`<section class="card"><h2>Care Plans</h2><p>The resident photographs are presented as informal care-plan profile photos taken in the home.</p>${residentCards()}</section>`,'Care Plans')}
function go(x){if(x==='Home')dashboard();else if(x==='Residents')residentsPage();else if(x==='Medication')medication();else if(x==='Tasks')tasks();else if(x==='Care Plans')carePlans();else shell(`<section class="card"><h2>${x}</h2><p>This section is ready for the next expansion.</p></section>`,x)}
dashboard();